[workspace]
members = [
    'qttypes',
    'qmetaobject_impl',
    'qmetaobject',
    'examples/todos',
    'examples/graph',
    'examples/qmlextensionplugins',
    'examples/webengine',
]


[profile.dev]
rpath = true  # So the examples run on the CI with macos
